project:
  type: website
  output-dir: docs

website:
  title: "Vector- en functieruimten -- Slides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/H1.qmd
        text: H1
      - href: slides/H2.qmd
        text: H2
      - href: slides/H3.qmd
        text: H3
      - href: slides/H4.qmd
        text: H4
      - href: slides/H5.qmd
        text: H5
      - href: slides/H6.qmd
        text: H6
      - href: slides/H7.qmd
        text: H7
      - href: slides/H8.qmd
        text: H8
      - href: slides/H9.qmd
        text: H9

format:
  html:
    theme: cosmo
    html-math-method: katex
    toc: true
