# Render the slides without editing the .qmd front matter.
#
#   make site                         website (HTML, cosmo) into docs/, as published
#   make revealjs                     all chapters as reveal.js into _presentations/slides/
#   make revealjs CH=H3               one chapter
#   make revealjs CH=H3 THEME=night   one chapter with a different reveal.js theme
#   make preview CH=H3                live reveal.js preview in the browser
#   make clean                        remove _presentations/ (keeps the KaTeX cache)
#
# FORMAT selects both the Quarto profile (_quarto-$(FORMAT).yml) and the output format,
# so adding e.g. _quarto-typst.yml makes `make render FORMAT=typst CH=H3` work.

FORMAT ?= revealjs
CH     ?= $(basename $(notdir $(wildcard slides/H*.qmd)))
THEME  ?=

QUARTO ?= quarto
# THEME goes through a generated profile rather than `-M theme:...`: Quarto only compiles
# a reveal.js theme's SCSS when the theme is set in YAML, so -M yields a missing stylesheet.
# Earlier profiles take precedence in Quarto, so the theme profile goes first.
PROFILE = $(if $(THEME),theme$(comma))$(FORMAT)
FLAGS   = --profile $(PROFILE) --to $(FORMAT)
comma  := ,

# reveal.js decks load KaTeX from _presentations/katex/ (see _quarto-revealjs.yml), so they
# work without internet. It is downloaded once into the gitignored .cache/ and copied from
# there; only that first download needs a connection. The website in docs/ keeps the CDN.
KATEX_VERSION := 0.18.10
KATEX_CACHE   := .cache/katex-$(KATEX_VERSION)
KATEX_DIR     := _presentations/katex
KATEX         := $(if $(filter revealjs,$(FORMAT)),$(KATEX_DIR)/katex.min.js)
# Theme fonts loaded from Google Fonts get the same treatment, cached in .cache/fonts/ by
# tools/localize_fonts.py, which the revealjs profile runs as a Quarto post-render script.

define THEME_PROFILE
# Generated by `make ... THEME=$(THEME)`; do not edit.
format:
  $(FORMAT):
    theme: $(THEME)
endef
export THEME_PROFILE

.PHONY: site render revealjs preview clean theme-profile

site:
	$(QUARTO) render

theme-profile:
	@rm -f _quarto-theme.yml
	@$(if $(THEME),echo "$$THEME_PROFILE" > _quarto-theme.yml)

render: theme-profile $(KATEX)
	@for ch in $(CH); do \
		echo "== $$ch ($(FORMAT))"; \
		$(QUARTO) render slides/$$ch.qmd $(FLAGS) || exit 1; \
	done

revealjs:
	@$(MAKE) --no-print-directory render FORMAT=revealjs

preview: theme-profile $(KATEX)
	@test $(words $(CH)) -eq 1 || { echo "preview needs a single chapter, e.g. make preview CH=H3"; exit 1; }
	$(QUARTO) preview slides/$(CH).qmd $(FLAGS)

$(KATEX_CACHE)/katex.min.js:
	@echo "== downloading KaTeX $(KATEX_VERSION)"
	@mkdir -p $(KATEX_CACHE)
	curl -sSfL https://registry.npmjs.org/katex/-/katex-$(KATEX_VERSION).tgz \
		| tar -xz -C $(KATEX_CACHE) --strip-components=2 \
			package/dist/katex.min.js package/dist/katex.min.css package/dist/fonts

$(KATEX_DIR)/katex.min.js: $(KATEX_CACHE)/katex.min.js
	@mkdir -p $(KATEX_DIR)
	cp -r $(KATEX_CACHE)/. $(KATEX_DIR)/

clean:
	rm -rf _presentations _quarto-theme.yml
