---
title: "Hoofdstuk 4 - Normen en afstanden"
author: "Jutho Haegeman"
date: "10/17/2023"
# format:
#   revealjs:
#     theme: solarized
#     chalkboard: true
---

## Doel van dit hoofdstuk


::: {.hidden}
$$
% Math operators
\DeclareMathOperator{\Aut}{Aut}
\DeclareMathOperator{\End}{End}
\DeclareMathOperator{\Hom}{Hom}
\DeclareMathOperator{\GL}{GL}
\DeclareMathOperator{\SL}{SL}
\DeclareMathOperator{\Unitary}{U}
\DeclareMathOperator{\Orthogonal}{O}
\DeclareMathOperator{\SU}{SU}
\DeclareMathOperator{\SO}{SO}
\DeclareMathOperator{\Aff}{Aff}
\DeclareMathOperator{\dom}{dom}
\DeclareMathOperator{\cod}{codom}
\DeclareMathOperator{\D}{\mathcal{D}}
\DeclareMathOperator{\E}{\mathcal{E}}
\DeclareMathOperator{\R}{\mathcal{R}}
\DeclareMathOperator{\Schw}{\mathcal{S}}
\DeclareMathOperator{\im}{im}
%\DeclareMathOperator{\ker}{ker}
%\DeclareMathOperator{\dim}{dim}
\DeclareMathOperator{\codim}{codim}
\DeclareMathOperator{\convhull}{co}

\newcommand{\opgreek}[1]{\begingroup\mathgroup-1 #1\endgroup}
\DeclareMathOperator{\rank}{rank}
\DeclareMathOperator{\nullity}{nullity}

\DeclareMathOperator{\Pv}{Pv}

\DeclareMathOperator{\tr}{tr}
\DeclareMathOperator{\sgn}{sgn}
\DeclareMathOperator{\id}{id}
\DeclareMathOperator{\adj}{adj}

\DeclareMathOperator*{\varmin}{min}
\DeclareMathOperator*{\varmax}{max}
\DeclareMathOperator*{\argmin}{arg\ min}
\DeclareMathOperator*{\argmax}{arg\ max}
\DeclareMathOperator{\order}{\mathscr{O}}
\DeclareMathOperator{\sign}{sgn}
\DeclareMathOperator{\spanop}{span}
\DeclareMathOperator{\arctanh}{arctanh}
\DeclareMathOperator{\arccosh}{arccosh}
\DeclareMathOperator{\arcsinh}{arcsinh}
\DeclareMathOperator{\arccot}{arccot}
\DeclareMathOperator{\sinc}{sinc}


\newcommand{\commutator}[2]{{\left[#1,#2\right]}}
\newcommand{\anticommutator}[2]{{\left\{#1,#2\right\}}}

\DeclareMathOperator{\real}{Re}
\DeclareMathOperator{\imag}{Im}
\newcommand{\conj}[1]{{\overline{#1}}}
\newcommand{\abs}[1]{{\left\lvert#1\right\rvert}}
\newcommand{\norm}[1]{{\left\lVert#1\right\rVert}}
\newcommand{\inner}[2]{{\left\langle#1,#2\right\rangle}}

\newcommand{\drm}{{\mathrm{d}}}
\newcommand{\erm}{{\mathrm{e}}}
\newcommand{\irm}{{\mathrm{i}}}


% VECTORS
\newcommand{\vect}[1]{{#1}}
\renewcommand{\vec}[1]{\boldsymbol{#1}} % specifically for vectors in F^n
\newcommand{\zerovec}{{o}}
\newcommand{\vu}{\vect{u}}
\newcommand{\vv}{\vect{v}}
\newcommand{\vw}{\vect{w}}
\newcommand{\ve}{\vect{e}}
\newcommand{\vf}{\vect{f}}
\newcommand{\vx}{\vect{x}}
\newcommand{\vy}{\vect{y}}

% MATRICES
\newcommand{\mat}[1]{{\mathsf{#1}}}
\newcommand{\zeromat}{\mat{O}}
\newcommand{\idmat}{\mat{I}}

% SCALARS
\newcommand{\scalara}{{a}}
\newcommand{\scalarb}{{b}}
\newcommand{\scalarc}{{c}}

% LINEAR MAPS
\DeclareMathAlphabet{\mymathbb}{U}{BOONDOX-ds}{m}{n}
\newcommand{\map}[1]{{\hat{#1}}}
\newcommand{\idmap}{\map{1}}
\newcommand{\zeromap}{\map{0}}

\newcommand{\transpose}{{\mathsf{T}}}
\newcommand{\hermitian}{{\mathsf{H}}}

\renewcommand{\d}{{\mathrm{d}}}

% FIELDS
\newcommand{\bbF}{{\mathbb{F}}}
\newcommand{\bbN}{{\mathbb{N}}}
\newcommand{\bbZ}{{\mathbb{Z}}}
\newcommand{\bbQ}{{\mathbb{Q}}}
\newcommand{\bbR}{{\mathbb{R}}}
\newcommand{\bbC}{{\mathbb{C}}}
\newcommand{\bbH}{{\mathbb{H}}}
\newcommand{\bbT}{{\mathbb{T}}}

% RELATIONS
\newcommand{\subspace}{{\preccurlyeq}}
\newcommand{\supspace}{{\succcurlyeq}}

%\newcommand{\vz}{{\bm{z}}}
%\newcommand{\ovz}{{\overline{\bm{z}}}}
%\newcommand{\oz}{{\overline{z}}}
%\newcommand{\vu}{{\bm{u}}}
%\newcommand{\ovu}{{\overline{\bm{u}}}}
%\newcommand{\ou}{{\overline{u}}}
%\newcommand{\vr}{{\bm{r}}}
%\newcommand{\ovr}{{\overline{\bm{r}}}}
%\newcommand{\orr}{{\overline{r}}}

\newcommand{\eps}{{\varepsilon}}
\newcommand{\levicivita}{{\epsilon}}

\newcommand{\sx}{{\sigma^x}}
\newcommand{\sy}{{\sigma^y}}
\newcommand{\sz}{{\sigma^z}}
\renewcommand{\sp}{{\sigma^+}}
\newcommand{\sm}{{\sigma^-}}
%

\DeclareMathOperator*{\sumint}{%
\mathchoice%
  {\ooalign{$\displaystyle\sum$\cr\hidewidth$\displaystyle\int$\hidewidth\cr}}
  {\ooalign{\raisebox{.14\height}{\scalebox{.7}{$\textstyle\sum$}}\cr\hidewidth$\textstyle\int$\hidewidth\cr}}
  {\ooalign{\raisebox{.2\height}{\scalebox{.6}{$\scriptstyle\sum$}}\cr$\scriptstyle\int$\cr}}
  {\ooalign{\raisebox{.2\height}{\scalebox{.6}{$\scriptstyle\sum$}}\cr$\scriptstyle\int$\cr}}
}
$$
:::

* Concept van norm = lengte van een vector
* Norm geeft aanleiding tot een afstand tussen vectoren
* Vormt de basis om concepten uit analyse te importeren

  (rijen, reeksen, continuïteit, …)

# Genormeerde vectorruimten

## Norm

Gegeven een vectorruimte $V$. Een norm is een afbeelding $V \to \bbR : \vv \mapsto \norm{\vv}$ die voldoet aan

* absolute homogeniteit: $\norm{\scalara \vv} = \abs{\scalara} \norm{\vv}$

  $\Rightarrow \norm{\zerovec} = 0$ , 
* subadditiviteit / driehoeksongelijkheid: $\norm{\vv + \vw } \leq \norm{\vv} + \norm{\vw}$

  $\Rightarrow \norm{\zerovec} = 0 \leq \norm{\vv} + \norm{-\vv} = 2 \norm{vv}$ 

* positief definiet: $\norm{vv} = 0 \Leftrightarrow \vv = 0$

Voor de eerste eigenschap hebben we op het veld van scalairen $\bbF$ een **absolute waarde** $\abs{\scalara}$ nodig. Voor $\bbR$ en $\bbC$ komt dit overeen met de gekende definitie. 

## Voorbeelden:

* $V = \bbF^n$: $\norm{\vv} = \sum_{i=1}^n \abs{v^i}$
* $V = \bbR^2$: $\norm{(x,y)} = \sqrt{x^2 + y^2}$
* $V = C(I,\bbF)$ voor een interval $I=[a,b] \subseteq \bbR$: $\norm{f} = \int_I \abs{f(x)}\,\drm x$ (zie later)

## Hölder $p$-norm

Voor $V = \bbF^n$ hebben we een familie van normen

$$\norm{\vv}_p = \left[\sum_{i=1}^{n} \abs{v^i}^p\right]^{1/p}$$

inclusief de limiet $p\to \infty$:

$$\norm{\vv}_\infty = \max \{\abs{\vv^i}, i=1,\ldots,n\}$$

## Hölder $p$-norm

* $\norm{\cdot}_p$ is absoluut homogeen en positief definiet per constructie.

* driehoeksongelijkheid kunnen we in een aantal stappen bewijzen, waarvoor we $q = p/(p-1)$ invoeren, of dus $1/p + 1/q = 1$ (inclusief $p=0 \leftrightarrow q=\infty$ en vice versa):

  * Young's ongelijkheid: $\forall a,b \in \bbR_{\geq 0}: ab \leq \frac{a^p}{p} + \frac{b^q}{q}$
  * Hölder's ongelijkheid: $\sum_{i=1}^n \abs{v^i}\abs{w^i} \leq \norm{v}_p \norm{w}_q$
  * Minkowski's ongelijkheid: $\norm{\vv+\vw}_p \leq \norm{\vv}_p + \norm{\vw}_p$

## Hölder $p$-norm

Uitbreiding naar oneindig-dimensionale ruimten:

* $\ell^p(\bbN_0,\bbF) \subspace \bbF^{\bbN_0}$: de ruimte van alle rijen $(v^1,v^2,v^3,\ldots)$ waarvoor $\sum_{i=1}^{+\infty} \abs{v^i}^p$ convergeert naar een eindige waarde

    * norm $\norm{\vv}_\infty = \left[\sum_{i=1}^{+\infty} \abs{v^i}^p\right]^{1/p}$ is eindig

    * speciaal geval $p=\infty$:
    
      $\norm{\vv}_\infty = \sup\{\abs{v^i}, i\in \bbN_0\}$ (supremum norm)

      $\ell^\infty(\bbN_0,\bbF)$: ruimte van begrensde rijen

  Bewijs van eigenschappen norm als limiet $n\to\infty$ van bewijs voor $\bbF^n$.

## Hölder $p$-norm

Uitbreiding naar oneindig-dimensionale ruimten:

* Voor $V = C^0([a,b],\bbF)$: $\norm{f}_p = \left(\int_a^b \abs{f(x)}^p\,\drm x\right)^{1/p}$

  * Continuïteit en compactheid van interval $[a,b]$ noodzakelijk om goed gedefinieerd te zijn (geen divergenties), en voor de eigenschap $\norm{f}_p=0 \implies f=0$
  * Driehoeksongelijkheid kan op analoge manier bewezen worden
  * Meer over functies in H7

## Metrische ruimten

Gegegeven een verzameling $X$, een metriek of afstandsfunctie is een functie $d:X \times X \to \bbR_{\geq 0}$ met eigenschappen:

* $d(x,y) = 0 \iff x=y$
* $d(x,y) = d(y,x)$
* $d(x,y) + d(y,z) \geq d(x,z)$

en dan noemen we $(X,d)$ een metrische ruimte
(ruimte wijst niet noodzakelijk op vectorruimte)

* Een genormeerde vectorruimte $(V,\norm{\cdot})$ wordt een metrische ruimte met de keuze $d(\vv,\vw) = \norm{\vv-\vw}$

## Metrische ruimten {.smaller}

Belang van metrische ruimten is dat we concepten uit analyse van functies $\bbR \to \bbR$ kunnen veralgemenen:

* Convergentie van een rij $(x_n \in X)_{n \in \bbN_0}$:

  * $\lim_{n \to \infty} x_n = x \iff \lim_{n \to \infty} d(x_n,x) = 0$

  * of dus: $\forall \epsilon > 0, \exists N_\epsilon \in \bbN_0$ zodat $n \geq N_\epsilon \implies d(x,x_n) \leq \epsilon$


* Continuïteit van $\Phi:X \to Y$ tussen metrische ruimten $(X,d_X)$ en $(Y,d_Y)$:

  * $\Phi$ is continu in $x \in X$: $\lim_{n \to \infty} \Phi(x_n) = \Phi(x)$ voor alle rijen $(x_n)_{n \in\bbN_0}$ met $\lim_{n\to\infty} x_n = x$
  * $\Phi$ is continu in $x \in X$: $\forall \epsilon > 0$, $\exists \delta_{\epsilon} > 0$ zodat $d_X(x',x) < \delta_\epsilon \implies d_Y(\Phi(x'),\Phi(x))$
  * $\Phi$ continu in volledig $X$: $\lim_{n\to\infty}\Phi(x_n) = \Phi(\lim_{n\to\infty} x_n)$ voor alle convergerende rijen 

::: aside
Voor een continue afbeelding $\Phi$ kan $\delta_\epsilon$ in de tweede definitie nog steeds afhangen van $x$. Is dat niet nodig, dan heet $\Phi$ ook "uniform continu".
:::

## Metrische ruimten

* Een afbeelding $\Phi:X \to Y$ tussen metrische ruimten $(X,d_X)$ en $(Y,d_Y)$ is **isometrisch** als $d_Y(\Phi(x),\Phi(x')) = d_X(x,x')$ voor alle $x,x'\in X$
  * Een isometrische afbeelding is automatisch (uniform) continu ($\delta_\epsilon = \epsilon$)
  * Een isometrische afbeelding is automatisch injectief
  * Een bijectieve isometrische afbeelding definieert een isomorfisme tussen $(X, d_X)$ en $(Y, d_Y)$

## Metrische ruimten {.smaller}

Topologische concepten in een metrische ruimte $(X,d)$:

* Open bol: $B_r(x) = \{x'\in X| d(x,x') \leq r\}$
* Open (deel)verzameling $S$: $\forall x \in S, \exists \epsilon>0$ zodat $B_r(x) \subseteq S$
* Gesloten deelverzameling $S$ als $S^\text{c} = X \setminus S$ open is
  * $\Rightarrow$ een convergerende rij $(x_n \in S)$ voldoet aan $\lim_{n\to\infty x_n} \in S$
  * $X$ and $\{\}$ zijn zowel open als gesloten
* Sluiting $\overline{S}$: kleinste gesloten verzameling die $S$ bevat = $S$ en al zijn limietpunten
* Dichte deelverzameling $S$: als $\overline{S} = X$
* Begrensde verzameling $S$: $\exists M \in \bbR_{\geq 0}$ zodat $d(x,y)<M, \forall x,y \in S$
* Compacte verzameling: zie verderop
* $X$ is **separabel** (scheidbaar?) als $X$ een aftelbare dichte deelverzameling heeft

## Continuïteit in genormeerde vectorruimte {.smaller}

We beschouwen nu een genormeerde vectorruimte $(V,\norm{\cdot})$ als metrische ruimte met metriek $d(\vv,\vw) = \norm{\vv-\vw}$

* De norm $\norm{\cdot}:V\to \bbR$ is zelf een continue afbeelding (bewijs aan bord)

  $\Rightarrow$ voor een convergente rij $(v_n \in V)_{n\in\bbN_0}$ is de geassocieerde rij $(\norm{\vv_n})_{n\in\bbN_0}$ convergent
* Vector optelling $+:V \times V \to V$ en scalaire vermenigvuldiging $\bbF \times V \to V$ zijn continue afbeeldingen^[Hiervoor hebben we het volgende nodig: de productverzameling $X \times Y$ van twee metrische ruimten $(X, d_X)$ en $(Y, d_Y)$ is metrische ruimte, bevoorbeeld met metriek $d_{X,Y}((x,y), (x',y')) = d_X(x,x') + d_Y(y,y')$}]

## Convergentie in functieruimten {.smaller}

Beschouw opnieuw $C^0([a,b],\bbF)$ met nu de $p=\infty$-norm, welke zich herleidt tot:^[Extremumstelling van Weierstrass: $\sup$ wordt $\max$ voor continue $f$ begrensd interval $[a,b]$]

$$\norm{f}_p = \sup_{x\in [a,b]}\abs{f(x)} = \max_{x\in[a,b]}\abs{f(x)}$$

Convergentie: $\lim_{n\to \infty} f_n = f$ als

* $\max_{x\in [a,b]} \abs{f_n(x)-f(x)} < \epsilon$ voor alle $n > N_\epsilon$
* $\abs{f_n(x)-f(x)} < \epsilon$ voor alle $x \in [a,b]$ voor alle $n > N_\epsilon$

  $\Rightarrow$ **uniforme convergentie** van een reeks

  $\Rightarrow$ $\norm{f}_{\infty}$ voor continue functies wordt de uniform-norm genoemd

* contrast met **puntsgewijze convergentie**:

  $\abs{f_n(x)-f(x)} < \epsilon$ voor alle $n > N_{\epsilon,x}$ voor alle $x \in [a,b]$

  kan niet worden bekomen met behulp van norm (tegenvoorbeeld aan bord)

## Equivalentie van normen {.smaller}

* Twee normen voor een vectorruimte $V$ zijn equivalent als ze aanleiding geven tot dezelfde definitie van convergerende rijen (met dan dezelfde limietpunten)

* Stelling: twee normen $\norm{\cdot}_a$ en $\norm{\cdot}_b$ zijn equivalent als en slechts als er constanten $C \geq c > 0$ bestaan zodat $c \norm{\vv}_a \leq \norm{\vv}_b \leq C\norm{\vv}_a$ voor alle $\vv \in V$

  (bewijs aan bord)

* Stelling: voor een eindig-dimensionale vectorruimte $V$ zijn alle normen equivalent 

  (bewijs aan bord)

* Voorbeelden voor $\vec{v} \in \bbF^n$:
  * $\frac{\norm{\vv}_1}{\sqrt{n}} \leq \norm{\vec{v}}_2 \leq \norm{\vv}_1$
  * $\frac{\norm{\vv}_1}{n} \leq \norm{\vec{v}}_\infty \leq \norm{\vv}_1$

## Compacte verzameling (geen bewijzen)

* Een verzameling $U$ is compact als

  * Wanneer $U$ wordt bedekt door open verzamelingen $\mathcal{V}=\{V_1,V_2,\ldots,\}$ (i.e. $U \subseteq \bigcup \mathcal{V}$), dan wordt $U$ ook bedekt door een eindig aantal van die verzamelingen
  * Elke rij $(\vv_n \in U)$ heeft een convergerende deelrij met limietpunt in $U$
  
  (equivalente karakterisaties in metrische ruimten)

* Stelling: in een eindig-dimensionale vectorruimte $V$ is een deelverzameling $U$ compact als en slechts als $U$ begrensd en gesloten is (analoog aan Vectoranalayse).

## Compacte verzamelingen (geen bewijzen)

In een oneindig-dimensionale vectorruimte zijn gesloten begrensde deelverzamelingen niet compact.

* Voorbeeld: $C^0([a,b],\bbF)$ met $\norm{\cdot}_\infty$
  
  * Beschouw de gesloten eenheidsbol: $\overline{B_1(\zerovec)} = \{\vv \in V|\norm{\vv} \leq 1\}$
  * Beschouw de rij $\{f_n(x)=x^n\}$ met elke $\norm{f_n} = 1$. Er bestaat geen  convergente deelrij.

* Technisch (Riesz lemma): Beschouw een eigenlijke gesloten deelruimte $W\subspace V$. Voor elke $\epsilon \in (0,1)$ kunnen we een $\vv_\epsilon \in V$ vinden waarvoor $\norm{\vv_\epsilon}=1$ en $\norm{\vv_\epsilon - \vw} > \epsilon$ voor alle $w \in W$.

# Banachruimten (geen bewijzen)

## Cauchy rijen en compleetheid

* Een Cauchy-rij in een metrische ruimte $(X,d)$ is een rij $(x_n \in X)_{n\in\bbN_0}$ zodat $\forall \epsilon >0: \exists N_\epsilon \in \bbN$ met dan $n,m > N_\epsilon \implies d(x_n,x_m) < \epsilon$

  (intuïtief: elementen in de staart van de rij komen arbitrair dicht bij elkaar)

* Een convergente rij is altijd een Cauchy-rij
* Als elke Cauchy-rij convergeert wordt $X$ (metrisch) compleet genoemd
* Een genormeerde vectorruimte $(V,\norm{\cdot})$ die metrisch compleet is wordt een Banachruimte genoemd

## Banachruimten

Voorbeelden:

* Elke eindig-dimensionale vectorruimte, met om het even welke keuze van norm
* Elke eindig-dimensionale deelruimte $W$ van een oneindig-dimensionale vectorruimte $V$, met als norm de restrictie van $\norm{\cdot}$ tot $W$
* De ruimte $\ell^p(\bbF)$ van oneindige rijen met eindige $p$-norm (en dit voor alle $p \in [1,+\infty]$)
* Ruimte $C^0([a,b],\bbF)$ met maximumnorm/uniformnorm $\norm{\cdot}_\infty$ voor begrensd (compact) interval $[a,b]$

## Banachruimten

Tegenvoorbeeld:

* Ruimte $\bbF[x]$ van polynomen met norm $\norm{p}= \max_{x \in [a,b]} \abs{p(x)}$
  * $p_n(x) = \sum_{k=0}^n \frac{1}{k!}x^k$ definieert een Cauchy-rij
  * $\lim_{n\to\infty} p_n$ bestaat niet als polynoom

* Herinterpreteer $\bbF[x]$ als (eigenlijke) deelruimte van $C^0([a,b],\bbF)$
  * $\lim_{n\to\infty} p_n = \exp$ bestaat als continue functie

    $\Rightarrow$ een oneindige deelruimte van een Banachruimte is niet noodzakelijk gesloten

## Banachruimten: complete verzameling

Aangezien (oneindig-dimensionale) deelruimten $W \subspace V$ open kunnen zijn, kunnen we hun sluiting $\overline{W}$ bekijken. 

* Zoals eerder: als $\overline{W}=V$, dan is $W$ een **dichte** deelruimte

  Elke vector $\vv \in V$ kan arbitrair dicht benaderd worden door een vector $\vw \in W$:
  
  $\forall \epsilon > 0, \vv \in V : \exists \vw \in W$ zodat $\norm{\vv-\vw}<\epsilon$

* Een verzameling $S$ waarvoor $\bbF S$ dicht is, of dus $\overline{\bbF S}=V$, wordt een totale, fundamentele of complete verzameling genoemd

  (Contrast met H1: complete verzameling als $\bbF S = V$)

## Banachruimten: complete verzameling

Voorbeeld: stelling van Stone-Weierstrass

Equivalente formuleringen:

* Elke continue functie kan aribtrair dicht (in uniform-norm) benaderd worden door een veelterm
* $\bbF[x]$ is een dichte deelverzameling van $C^0([a,b],\bbF)$
* $\{x^n, n=0,1,2,\ldots\}$ is een complete verzameling voor $C^0([a,b],\bbF)$

## Banachruimten {.smaller}

Van rijen naar reeksen in genormeerde vectorruimten $(V,\norm{\cdot})$

* Convergentie van reeksen: als rij van partieelsommen convergeert

  $\sum_{n=1}^{+\infty} \vv_n	=\vv \iff  \lim_{n\to\infty} \sum_{k=1}^{n} \vv_k = \vv \iff \lim_{n\to \infty} \norm{\sum_{k=1}^{n} \vv_k - \vv } = 0$

* Een reeks $\sum_{n=1}^{+\infty} \vv_n$ is absoluut convergent als de reeks $\sum_{n=1}^{+\infty} \norm{\vv_n}$ convergeert

  (absolute convergentie is zeker geen nodige voorwaarde voor convergentie van een reeks)

* Stelling: Een genormeerde vectorruimte is metrisch compleet (Banachruimte) als en slechts als absolute convergentie een voldoende voorwaarde is voor convergentie van een reeks (elke absoluut convergente reeks convergeert).

## Banachruimten en basis {.smaller}

Convergentie van rijen en reeksen laat een nieuw concept van basis toe in Banachruimten $(V,\norm{\cdot})$

* Een *Schauder basis* is een rij $(\ve_n \in V)_{n \in \bbN_0}$ zodat voor elke vector $\vv \in V$ een rij van coefficiënten $(a^n \in \bbF)_{n \in \bbN_0}$ bestaat, zodat de reeks $\sum_{n =1}^{+\infty} a^n \ve_n$ convergeert naar $\vv$

* De rij $(x^n)_{n \in \bbN}$ is **geen (!!)** Schauder basis voor $(C^0([a,b],\bbF), \norm{\cdot}_{\infty})$:

  * een reeks $\sum_{n=0}^{+\infty} a_n x^n$ die convergeert met betrekking tot $\norm{\cdot}_{\infty}$ (uniforme convergentie) geeft sowieso aanleiding tot een analytische functie

  * een continue functie zoals $\abs{x}$ heeft geen convergente Taylorreeks

$\Rightarrow$ allerlei technische subtiliteiten die verdwijnen in het geval van Hilbertruimten (zie volgend hoofdstuk)